#LunarLander.yaml
env_id: LunarLander-v3
seed: 42
gamma: 0.99
buffer_size: 200000
batch_size: 256
lr: 5e-4
epsilon_start: 1.0
epsilon_end: 0.05
epsilon_decay_steps: 200000
target_update_interval: 1000
train_start: 10000
train_freq: 1
max_steps: 500000   